# Website details
name: Benim Sitem #sitename 
description: İlk Jeklly Sayfam #siteaçıklaması 
email: email@site.com
author: yazar.
lang: tr #tr  en
locale: en_EN #tr_TR yapabilirsiniz. en_EN

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/New_York
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://ssilistre.me/fastjeklly/ #buraya kendi adresinizi yazıcaksınız.

# Includes
addthisId: ""
disqusUsername: "" #disqus kullanıcı adınız.
googleAnalyticsId: "" #google analaytic idiniz

# Search engine verifications
bing: ""    #bu kısım tamemen arama motorları içindir. Buraya arama motoru kayıtları için verilen verif kodunu yazmalısınız.
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
